/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicOnboardingRouteImport } from './routes/_public/onboarding'
import { Route as AppStudyRouteImport } from './routes/_app/study'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAddCardRouteImport } from './routes/_app/add-card'
import { Route as AppStudyIndexRouteImport } from './routes/_app/study/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppStudyShuffleRouteImport } from './routes/_app/study/shuffle'
import { Route as AppStudyReviewRouteImport } from './routes/_app/study/review'
import { Route as AppStudyBrowseRouteImport } from './routes/_app/study/browse'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOnboardingRoute = PublicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PublicRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAddCardRoute = AppAddCardRouteImport.update({
  id: '/add-card',
  path: '/add-card',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyIndexRoute = AppStudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyShuffleRoute = AppStudyShuffleRouteImport.update({
  id: '/shuffle',
  path: '/shuffle',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudyReviewRoute = AppStudyReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudyBrowseRoute = AppStudyBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppStudyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/add-card': typeof AppAddCardRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/study': typeof AppStudyRouteWithChildren
  '/onboarding': typeof PublicOnboardingRoute
  '/study/browse': typeof AppStudyBrowseRoute
  '/study/review': typeof AppStudyReviewRoute
  '/study/shuffle': typeof AppStudyShuffleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/study/': typeof AppStudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/add-card': typeof AppAddCardRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/onboarding': typeof PublicOnboardingRoute
  '/study/browse': typeof AppStudyBrowseRoute
  '/study/review': typeof AppStudyReviewRoute
  '/study/shuffle': typeof AppStudyShuffleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/study': typeof AppStudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/add-card': typeof AppAddCardRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/study': typeof AppStudyRouteWithChildren
  '/_public/onboarding': typeof PublicOnboardingRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/study/browse': typeof AppStudyBrowseRoute
  '/_app/study/review': typeof AppStudyReviewRoute
  '/_app/study/shuffle': typeof AppStudyShuffleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/study/': typeof AppStudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-card'
    | '/dashboard'
    | '/settings'
    | '/study'
    | '/onboarding'
    | '/study/browse'
    | '/study/review'
    | '/study/shuffle'
    | '/api/auth/$'
    | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-card'
    | '/dashboard'
    | '/settings'
    | '/onboarding'
    | '/study/browse'
    | '/study/review'
    | '/study/shuffle'
    | '/api/auth/$'
    | '/study'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/add-card'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/study'
    | '/_public/onboarding'
    | '/_public/'
    | '/_app/study/browse'
    | '/_app/study/review'
    | '/_app/study/shuffle'
    | '/api/auth/$'
    | '/_app/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/onboarding': {
      id: '/_public/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PublicOnboardingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add-card': {
      id: '/_app/add-card'
      path: '/add-card'
      fullPath: '/add-card'
      preLoaderRoute: typeof AppAddCardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study/': {
      id: '/_app/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof AppStudyIndexRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/study/shuffle': {
      id: '/_app/study/shuffle'
      path: '/shuffle'
      fullPath: '/study/shuffle'
      preLoaderRoute: typeof AppStudyShuffleRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/review': {
      id: '/_app/study/review'
      path: '/review'
      fullPath: '/study/review'
      preLoaderRoute: typeof AppStudyReviewRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/browse': {
      id: '/_app/study/browse'
      path: '/browse'
      fullPath: '/study/browse'
      preLoaderRoute: typeof AppStudyBrowseRouteImport
      parentRoute: typeof AppStudyRoute
    }
  }
}

interface AppStudyRouteChildren {
  AppStudyBrowseRoute: typeof AppStudyBrowseRoute
  AppStudyReviewRoute: typeof AppStudyReviewRoute
  AppStudyShuffleRoute: typeof AppStudyShuffleRoute
  AppStudyIndexRoute: typeof AppStudyIndexRoute
}

const AppStudyRouteChildren: AppStudyRouteChildren = {
  AppStudyBrowseRoute: AppStudyBrowseRoute,
  AppStudyReviewRoute: AppStudyReviewRoute,
  AppStudyShuffleRoute: AppStudyShuffleRoute,
  AppStudyIndexRoute: AppStudyIndexRoute,
}

const AppStudyRouteWithChildren = AppStudyRoute._addFileChildren(
  AppStudyRouteChildren,
)

interface AppRouteChildren {
  AppAddCardRoute: typeof AppAddCardRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyRoute: typeof AppStudyRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAddCardRoute: AppAddCardRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyRoute: AppStudyRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicOnboardingRoute: typeof PublicOnboardingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicOnboardingRoute: PublicOnboardingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
